import os
import markdown
import logging
import datetime

try:
    from weasyprint import HTML
    WEASYPRINT_AVAILABLE = True
except ImportError:
    WEASYPRINT_AVAILABLE = False
    logging.warning("WeasyPrint not available. PDF generation will be disabled. Install system dependencies: brew install pango")

logger = logging.getLogger(__name__)

class ReportGenerator:
    def __init__(self, output_dir="../outputs/reports"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_report(self, analysis_result):
        """Generates Markdown and PDF reports."""
        job_id = analysis_result.get("job_id")
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # 1. Generate Markdown Content
        md_content = self._create_markdown(analysis_result, timestamp)
        
        # 2. Save Markdown
        md_filename = f"report_{job_id}.md"
        md_path = os.path.join(self.output_dir, md_filename)
        with open(md_path, "w") as f:
            f.write(md_content)
            
        # 3. Generate PDF
        pdf_filename = f"report_{job_id}.pdf"
        pdf_path = os.path.join(self.output_dir, pdf_filename)
        
        if WEASYPRINT_AVAILABLE:
            try:
                html_content = markdown.markdown(md_content, extensions=['tables', 'fenced_code'])
                # Add some basic styling for the PDF
                styled_html = f"""
                <html>
                <head>
                    <style>
                        body {{ font-family: sans-serif; line-height: 1.6; color: #333; }}
                        h1, h2, h3 {{ color: #0072B2; }}
                        code {{ background: #f4f4f4; padding: 2px 5px; border-radius: 3px; }}
                        pre {{ background: #f4f4f4; padding: 10px; border-radius: 5px; overflow-x: auto; }}
                        table {{ border-collapse: collapse; width: 100%; margin-bottom: 20px; }}
                        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                        th {{ background-color: #f2f2f2; }}
                        .score {{ font-size: 24px; font-weight: bold; color: #D55E00; }}
                    </style>
                </head>
                <body>
                    {html_content}
                </body>
                </html>
                """
                HTML(string=styled_html).write_pdf(pdf_path)
                logger.info(f"Generated PDF report at {pdf_path}")
            except Exception as e:
                logger.error(f"Failed to generate PDF: {e}")
                pdf_path = None
        else:
            logger.warning("WeasyPrint not available - PDF generation skipped. Markdown report saved.")
            pdf_path = None
            
        return md_path, pdf_path

    def _create_markdown(self, data, timestamp):
        analysis = data.get("analysis", {})
        job_name = data.get("job_name", "Unknown Job")
        job_id = data.get("job_id")
        
        md = f"""# Databricks AI Workflow Health Report
**Job Name:** {job_name}  
**Job ID:** {job_id}  
**Date:** {timestamp}

---

## Executive Summary
**Workflow Health Score:** {analysis.get('workflow_health_score', 'N/A')}/100  
**Documentation Score:** {analysis.get('docs_score', 'N/A')}/100

### Cluster Recommendation
**Size:** {analysis.get('cluster_recommendations', {}).get('size', 'N/A')}  
**Reasoning:** {analysis.get('cluster_recommendations', {}).get('reasoning', 'N/A')}

---

## Top 5 Fixes for PS Teams
"""
        for fix in analysis.get('top_fixes', [])[:5]:
            md += f"- {fix}\n"
            
        md += "\n## Detailed Issues\n"
        md += "| Type | Severity | Description |\n|---|---|---|\n"
        for issue in analysis.get('issues', []):
            md += f"| {issue.get('type')} | {issue.get('severity')} | {issue.get('description')} |\n"
            
        md += "\n## Code Improvements\n"
        if analysis.get('sql_rewrite_suggestions'):
            md += "### SQL Suggestions\n"
            for item in analysis.get('sql_rewrite_suggestions', []):
                md += f"- {item}\n"
                
        if analysis.get('python_code_improvements'):
            md += "\n### Python Suggestions\n"
            for item in analysis.get('python_code_improvements', []):
                md += f"- {item}\n"

        md += """
---
## Suggested Next Steps for Engagement Success
1. Review "High" severity issues immediately.
2. Apply cluster sizing recommendations to reduce DBU costs.
3. Refactor notebooks to improve modularity and testability.

*Generated by Databricks PS AI Workflow Inspector*
"""
        return md
